// Run this in MongoDB Atlas or locally with: node seed-data.js
// Make sure you have mongoose installed: npm install mongoose

import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();
const destinationSchema = new mongoose.Schema({
  name: String,
  city: String,
  category: [String],
  interests: [String],
  latitude: Number,
  longitude: Number,
  rating: Number,
  popularityScore: Number,
  mustSee: Boolean,
  visitDurationHours: Number,
  entryFee: Number,
  description: String,
  openingHours: String,
  bestSeason: String,
  imageUrl: String
}, {
  timestamps: true  // ✅ CORRECT - second parameter
});

const Destination = mongoose.model('Destination', destinationSchema);

const destinations = [
  // ============= THANJAVUR (9 destinations) =============
  {
    name: 'Brihadeeswarar Temple (Big Temple)',
    city: 'Thanjavur',
    category: ['temple'],
    interests: ['temple', 'history', 'architecture'],
    latitude: 10.7865,
    longitude: 79.1373,
    rating: 4.8,
    popularityScore: 95,
    mustSee: true,
    visitDurationHours: 2.5,
    entryFee: 0,
    description: 'UNESCO World Heritage site with a 216-foot granite tower. One of the greatest achievements of Chola architecture.',
    openingHours: '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Brihadeeswarar+Temple'
  },
  {
    name: 'Thanjavur Palace',
    city: 'Thanjavur',
    category: ['palace', 'history'],
    interests: ['history', 'architecture'],
    latitude: 10.7854,
    longitude: 79.1468,
    rating: 4.3,
    popularityScore: 75,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 30,
    description: 'Historic palace with Maratha and Nayak architectural styles. Houses the Saraswathi Mahal Library.',
    openingHours: '9:00 AM - 1:00 PM, 1:30 PM - 5:00 PM',
    bestSeason: 'November to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Thanjavur+Palace'
  },
  {
    name: 'Saraswathi Mahal Library',
    city: 'Thanjavur',
    category: ['library', 'culture'],
    interests: ['history', 'culture'],
    latitude: 10.7854,
    longitude: 79.1468,
    rating: 4.5,
    popularityScore: 70,
    mustSee: true,
    visitDurationHours: 1.5,
    entryFee: 50,
    description: 'One of the oldest libraries in India with over 49,000 manuscripts and ancient texts.',
    openingHours: '9:00 AM - 1:00 PM, 1:30 PM - 4:30 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Saraswathi+Mahal'
  },
  {
    name: 'Schwartz Church',
    city: 'Thanjavur',
    category: ['church'],
    interests: ['history', 'architecture'],
    latitude: 10.7865,
    longitude: 79.1340,
    rating: 4.2,
    popularityScore: 60,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 0,
    description: 'Historic church built in 1779, showcasing Indo-European architectural style.',
    openingHours: '8:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Schwartz+Church'
  },
  {
    name: 'Vijayanagar Fort',
    city: 'Thanjavur',
    category: ['fort'],
    interests: ['history', 'architecture'],
    latitude: 10.7900,
    longitude: 79.1350,
    rating: 4.1,
    popularityScore: 55,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 20,
    description: 'Ancient fort ruins showcasing Vijayanagar empire architecture and history.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'November to January',
    imageUrl: 'https://via.placeholder.com/400x300?text=Vijayanagar+Fort'
  },
  {
    name: 'Airavatesvara Temple',
    city: 'Thanjavur',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 10.9185,
    longitude: 79.1585,
    rating: 4.4,
    popularityScore: 65,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient Chola temple with intricate stone carvings and relief sculptures.',
    openingHours: '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Airavatesvara+Temple'
  },
  {
    name: 'Nayak Palace Art Gallery',
    city: 'Thanjavur',
    category: ['museum'],
    interests: ['history', 'culture'],
    latitude: 10.7854,
    longitude: 79.1468,
    rating: 4.0,
    popularityScore: 50,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 40,
    description: 'Gallery displaying Thanjavur paintings, sculptures, and artifacts.',
    openingHours: '9:00 AM - 5:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Art+Gallery'
  },
  {
    name: 'Parthasarathy Temple',
    city: 'Thanjavur',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 10.7945,
    longitude: 79.1295,
    rating: 4.3,
    popularityScore: 62,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Beautiful Chola temple dedicated to Lord Krishna.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Parthasarathy+Temple'
  },
  {
    name: 'Thanjavur Marathi Palace',
    city: 'Thanjavur',
    category: ['palace'],
    interests: ['history', 'architecture'],
    latitude: 10.7870,
    longitude: 79.1460,
    rating: 4.1,
    popularityScore: 58,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 25,
    description: 'Marathi-era palace with historical significance and beautiful gardens.',
    openingHours: '9:00 AM - 5:00 PM',
    bestSeason: 'November to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Marathi+Palace'
  },

  // ============= KANCHIPURAM (10 destinations) =============
  {
    name: 'Devarajaswami Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 12.8345,
    longitude: 79.7002,
    rating: 4.6,
    popularityScore: 85,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Ancient Vaishnavite temple with intricate carvings and 5 gopurams.',
    openingHours: '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Devarajaswami+Temple'
  },
  {
    name: 'Kailasanatha Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'history', 'architecture'],
    latitude: 12.8295,
    longitude: 79.7042,
    rating: 4.7,
    popularityScore: 90,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'One of the oldest temples built in the 7th century. Excellent Pallava architecture.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Kailasanatha+Temple'
  },
  {
    name: 'Kanchi Kamakshi Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 12.8370,
    longitude: 79.7080,
    rating: 4.5,
    popularityScore: 80,
    mustSee: true,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Sacred temple dedicated to Goddess Kamakshi. One of the 51 Shakti Peethas.',
    openingHours: '5:00 AM - 12:30 PM, 4:00 PM - 9:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Kamakshi+Temple'
  },
  {
    name: 'Ekambareswarar Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 12.8295,
    longitude: 79.7085,
    rating: 4.4,
    popularityScore: 75,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Ancient Shiva temple with massive gopuram and mango tree shrine.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Ekambareswarar+Temple'
  },
  {
    name: 'Kanchipuram Silk Saree Showrooms',
    city: 'Kanchipuram',
    category: ['shopping'],
    interests: ['culture'],
    latitude: 12.8340,
    longitude: 79.7005,
    rating: 4.3,
    popularityScore: 70,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Famous silk saree weaving centers. Watch artisans create traditional sarees.',
    openingHours: '9:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Silk+Sarees'
  },
  {
    name: 'Vedanthangal Bird Sanctuary',
    city: 'Kanchipuram',
    category: ['nature'],
    interests: ['nature'],
    latitude: 12.5400,
    longitude: 79.8500,
    rating: 4.4,
    popularityScore: 82,
    mustSee: false,
    visitDurationHours: 3,
    entryFee: 50,
    description: 'Pristine lake sanctuary for migratory birds. Perfect for bird watching.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'November to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Bird+Sanctuary'
  },
  {
    name: 'Varadharaja Perumal Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 12.8385,
    longitude: 79.6985,
    rating: 4.5,
    popularityScore: 78,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Beautiful Vaishnavite temple with ornate pillars and intricate carvings.',
    openingHours: '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Varadharaja+Temple'
  },
  {
    name: 'Kamakshi Amman Temple Museum',
    city: 'Kanchipuram',
    category: ['museum'],
    interests: ['history', 'culture'],
    latitude: 12.8370,
    longitude: 79.7080,
    rating: 4.0,
    popularityScore: 55,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 30,
    description: 'Museum showcasing temple artifacts, sculptures, and historical items.',
    openingHours: '9:00 AM - 5:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Museum'
  },
  {
    name: 'Ulagalantha Perumal Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 12.8250,
    longitude: 79.7150,
    rating: 4.2,
    popularityScore: 60,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 0,
    description: 'Ancient temple dedicated to Lord Vishnu with beautiful architecture.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Ulagalantha+Temple'
  },
  {
    name: 'Ashtabujanam Temple',
    city: 'Kanchipuram',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 12.8300,
    longitude: 79.7120,
    rating: 4.1,
    popularityScore: 52,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 0,
    description: 'Unique temple with an eight-armed idol of Durga.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Ashtabujanam+Temple'
  },

  // ============= MADURAI (10 destinations) =============
  {
    name: 'Meenakshi Amman Temple',
    city: 'Madurai',
    category: ['temple'],
    interests: ['temple', 'history', 'architecture'],
    latitude: 9.9252,
    longitude: 78.1198,
    rating: 4.8,
    popularityScore: 98,
    mustSee: true,
    visitDurationHours: 3,
    entryFee: 0,
    description: 'One of the oldest and most significant temples in India. UNESCO site with 4 magnificent gopurams.',
    openingHours: '5:00 AM - 9:30 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Meenakshi+Temple'
  },
  {
    name: 'Thirumalai Nayak Palace',
    city: 'Madurai',
    category: ['palace'],
    interests: ['history', 'architecture'],
    latitude: 9.9215,
    longitude: 78.1220,
    rating: 4.6,
    popularityScore: 85,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 50,
    description: 'Magnificent palace built in 1636 with Indo-Saracenic architecture.',
    openingHours: '9:00 AM - 1:00 PM, 2:00 PM - 5:30 PM',
    bestSeason: 'November to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Thirumalai+Palace'
  },
  {
    name: 'Madurai Museum',
    city: 'Madurai',
    category: ['museum'],
    interests: ['history', 'culture'],
    latitude: 9.9180,
    longitude: 78.1150,
    rating: 4.2,
    popularityScore: 65,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 25,
    description: 'Museum with Pandyan dynasty artifacts, sculptures, and historical documents.',
    openingHours: '10:00 AM - 5:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Madurai+Museum'
  },
  {
    name: 'Vandiyur Mariamman Teppakulam',
    city: 'Madurai',
    category: ['lake'],
    interests: ['nature'],
    latitude: 9.9100,
    longitude: 78.1350,
    rating: 4.0,
    popularityScore: 60,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient temple tank with beautiful floating ceremony during Teppa Festival.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Teppakulam'
  },
  {
    name: 'Aayiram Kaal Mandapam',
    city: 'Madurai',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 9.9260,
    longitude: 78.1190,
    rating: 4.3,
    popularityScore: 70,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Hall of thousand pillars in Meenakshi Temple complex with intricate carvings.',
    openingHours: '5:00 AM - 9:30 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Aayiram+Kaal'
  },
  {
    name: 'Koodal Azhagar Temple',
    city: 'Madurai',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 9.9180,
    longitude: 78.1200,
    rating: 4.4,
    popularityScore: 72,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient Vaishnavite temple with beautiful sculptures and mythology carvings.',
    openingHours: '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Koodal+Azhagar'
  },
  {
    name: 'Kapaleshwara Temple',
    city: 'Madurai',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 9.9290,
    longitude: 78.1170,
    rating: 4.2,
    popularityScore: 68,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 0,
    description: 'Shiva temple with fascinating architecture and historical significance.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Kapaleshwara'
  },
  {
    name: 'Gandhi Memorial Museum',
    city: 'Madurai',
    category: ['museum'],
    interests: ['history', 'culture'],
    latitude: 9.9150,
    longitude: 78.1180,
    rating: 4.1,
    popularityScore: 62,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 20,
    description: 'Museum dedicated to Mahatma Gandhi with artifacts and photographs.',
    openingHours: '9:00 AM - 5:30 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Gandhi+Museum'
  },
  {
    name: 'Mandi Market',
    city: 'Madurai',
    category: ['market'],
    interests: ['culture'],
    latitude: 9.9240,
    longitude: 78.1210,
    rating: 4.0,
    popularityScore: 58,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Bustling traditional market with local crafts, flowers, and spices.',
    openingHours: '6:00 AM - 9:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Mandi+Market'
  },
  {
    name: 'Tirupparankundram Temple',
    city: 'Madurai',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 9.8950,
    longitude: 78.1200,
    rating: 4.3,
    popularityScore: 68,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient cave temple dedicated to Murugan with scenic views.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Tirupparankundram'
  },

  // ============= CHENNAI (10 destinations) =============
  {
    name: 'Parthasarathy Temple',
    city: 'Chennai',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 13.0499,
    longitude: 80.2717,
    rating: 4.5,
    popularityScore: 80,
    mustSee: true,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient Vaishnavite temple with beautiful carvings and pillars.',
    openingHours: '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Parthasarathy+Temple'
  },
  {
    name: 'Fort St. George',
    city: 'Chennai',
    category: ['fort'],
    interests: ['history', 'architecture'],
    latitude: 13.1626,
    longitude: 80.3500,
    rating: 4.4,
    popularityScore: 78,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 50,
    description: 'Historic fort built in 1644. Houses museums and government buildings.',
    openingHours: '9:00 AM - 5:00 PM',
    bestSeason: 'November to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Fort+St+George'
  },
  {
    name: 'Marina Beach',
    city: 'Chennai',
    category: ['beach'],
    interests: ['nature', 'relaxation'],
    latitude: 13.0499,
    longitude: 80.2831,
    rating: 4.2,
    popularityScore: 85,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Second longest urban beach in India. Great for walking and relaxation.',
    openingHours: '5:00 AM - 10:00 PM',
    bestSeason: 'October to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Marina+Beach'
  },
  {
    name: 'Government Museum',
    city: 'Chennai',
    category: ['museum'],
    interests: ['history', 'culture'],
    latitude: 13.0610,
    longitude: 80.2405,
    rating: 4.3,
    popularityScore: 72,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 50,
    description: 'One of India\'s oldest museums with sculptures, paintings, and artifacts.',
    openingHours: '9:30 AM - 5:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Government+Museum'
  },
  {
    name: 'San Thome Cathedral',
    city: 'Chennai',
    category: ['church'],
    interests: ['history', 'architecture'],
    latitude: 13.0479,
    longitude: 80.2789,
    rating: 4.2,
    popularityScore: 68,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 0,
    description: 'Neo-Gothic cathedral built over the tomb of apostle Thomas.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=San+Thome'
  },
  {
    name: 'Kapaleeshwarar Temple',
    city: 'Chennai',
    category: ['temple'],
    interests: ['temple', 'history'],
    latitude: 13.0441,
    longitude: 80.2686,
    rating: 4.4,
    popularityScore: 75,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient Shiva temple with intricate gopuram and beautiful sculptures.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Kapaleeshwarar'
  },
  {
    name: 'Guindy National Park',
    city: 'Chennai',
    category: ['nature'],
    interests: ['nature'],
    latitude: 13.0034,
    longitude: 80.2264,
    rating: 4.1,
    popularityScore: 70,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 100,
    description: 'Urban national park with blackbuck, spotted deer, and diverse flora.',
    openingHours: '9:00 AM - 5:30 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Guindy+Park'
  },
  {
    name: 'Thiruvanmiyur Beach',
    city: 'Chennai',
    category: ['beach'],
    interests: ['nature', 'relaxation'],
    latitude: 12.9921,
    longitude: 80.2484,
    rating: 4.0,
    popularityScore: 65,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Peaceful beach with temples and water sports activities.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to February',
    imageUrl: 'https://via.placeholder.com/400x300?text=Thiruvanmiyur'
  },
  {
    name: 'Sri Veeramakaliamman Temple',
    city: 'Chennai',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 13.0641,
    longitude: 80.2713,
    rating: 4.2,
    popularityScore: 63,
    mustSee: false,
    visitDurationHours: 1,
    entryFee: 0,
    description: 'Ancient temple dedicated to Goddess Kali in the heart of the city.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Veeramakali'
  },
  {
    name: 'Velachery Lake',
    city: 'Chennai',
    category: ['lake'],
    interests: ['nature', 'relaxation'],
    latitude: 12.9726,
    longitude: 80.2235,
    rating: 4.0,
    popularityScore: 58,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Scenic lake with walking trails and birdwatching opportunities.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Velachery+Lake'
  },

  // ============= OOTY (10 destinations) =============
  {
    name: 'Ooty Lake',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature', 'relaxation'],
    latitude: 11.4107,
    longitude: 76.6955,
    rating: 4.5,
    popularityScore: 85,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 50,
    description: 'Scenic artificial lake perfect for boating, picnicking, and photography.',
    openingHours: '7:00 AM - 6:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Ooty+Lake'
  },
  {
    name: 'Botanical Gardens',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature'],
    latitude: 11.4149,
    longitude: 76.6988,
    rating: 4.6,
    popularityScore: 88,
    mustSee: true,
    visitDurationHours: 2.5,
    entryFee: 40,
    description: 'Beautiful gardens with diverse plant species, fossil tree, and scenic views.',
    openingHours: '8:00 AM - 6:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Botanical+Gardens'
  },
  {
    name: 'Doddabetta Peak',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature'],
    latitude: 11.3851,
    longitude: 76.6953,
    rating: 4.4,
    popularityScore: 82,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 100,
    description: 'Highest peak in Nilgiris with 360-degree panoramic views.',
    openingHours: '9:00 AM - 5:30 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Doddabetta+Peak'
  },
  {
    name: 'Pykara Lake',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature', 'relaxation'],
    latitude: 11.4301,
    longitude: 76.6854,
    rating: 4.3,
    popularityScore: 75,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 30,
    description: 'Serene lake surrounded by eucalyptus forests and green meadows.',
    openingHours: '7:00 AM - 6:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Pykara+Lake'
  },
  {
    name: 'Ooty Toy Train',
    city: 'Ooty',
    category: ['heritage'],
    interests: ['nature', 'heritage'],
    latitude: 11.4107,
    longitude: 76.6955,
    rating: 4.4,
    popularityScore: 80,
    mustSee: true,
    visitDurationHours: 3,
    entryFee: 500,
    description: 'UNESCO heritage steam train ride through tea gardens and pine forests.',
    openingHours: '9:00 AM - 3:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Toy+Train'
  },
  {
    name: 'Mudumalai National Park',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature'],
    latitude: 11.2800,
    longitude: 76.4200,
    rating: 4.2,
    popularityScore: 72,
    mustSee: false,
    visitDurationHours: 3,
    entryFee: 200,
    description: 'Wildlife sanctuary with elephants, tigers, and diverse bird species.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Mudumalai+Park'
  },
  {
    name: 'Coonoor Tea Gardens',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature'],
    latitude: 11.3606,
    longitude: 76.8107,
    rating: 4.3,
    popularityScore: 78,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Picturesque tea plantations with guided tours and tea tastings.',
    openingHours: '9:00 AM - 5:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Tea+Gardens'
  },
  {
    name: 'St. Mary\'s Church',
    city: 'Ooty',
    category: ['church'],
    interests: ['history', 'architecture'],
    latitude: 11.4107,
    longitude: 76.6955,
    rating: 4.0,
    popularityScore: 60,
    mustSee: false,
    visitDurationHours: 0.5,
    entryFee: 0,
    description: 'Historic church built in 1829 with beautiful stained glass windows.',
    openingHours: '8:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=St+Mary+Church'
  },
  {
    name: 'Ooty Pine Forest',
    city: 'Ooty',
    category: ['nature'],
    interests: ['nature', 'relaxation'],
    latitude: 11.4200,
    longitude: 76.6850,
    rating: 4.2,
    popularityScore: 68,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Beautiful forest with walking trails, picnic spots, and serene environment.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'April to June, September to November',
    imageUrl: 'https://via.placeholder.com/400x300?text=Pine+Forest'
  },

  // ============= COIMBATORE (10 destinations) =============
  {
    name: 'Marudhamalai Murugan Temple',
    city: 'Coimbatore',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 11.0416,
    longitude: 76.9209,
    rating: 4.7,
    popularityScore: 95,
    mustSee: true,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Ancient hilltop temple dedicated to Lord Murugan. Scenic views of the valley.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Marudhamalai+Temple'
  },
  {
    name: 'Adiyogi Shiva Statue',
    city: 'Coimbatore',
    category: ['statue'],
    interests: ['spirituality'],
    latitude: 10.9723,
    longitude: 76.7405,
    rating: 4.8,
    popularityScore: 98,
    mustSee: true,
    visitDurationHours: 2.5,
    entryFee: 0,
    description: 'Tallest shiva statue in the world (112 feet). Iconic meditation center.',
    openingHours: '8:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Adiyogi+Statue'
  },
  {
    name: 'Perur Pateeswarar Temple',
    city: 'Coimbatore',
    category: ['temple'],
    interests: ['temple', 'history', 'architecture'],
    latitude: 10.9786,
    longitude: 76.9272,
    rating: 4.6,
    popularityScore: 90,
    mustSee: true,
    visitDurationHours: 1.5,
    entryFee: 0,
    description: 'Ancient Chola temple with intricate copper plates and stone carvings.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'October to March',
    imageUrl: 'https://via.placeholder.com/400x300?text=Perur+Temple'
  },
  {
    name: 'Siruvani Waterfalls',
    city: 'Coimbatore',
    category: ['nature'],
    interests: ['nature'],
    latitude: 10.9381,
    longitude: 76.6892,
    rating: 4.4,
    popularityScore: 85,
    mustSee: false,
    visitDurationHours: 3,
    entryFee: 50,
    description: 'Beautiful waterfall in Western Ghats. Popular for trekking and swimming.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'June to December',
    imageUrl: 'https://via.placeholder.com/400x300?text=Siruvani+Falls'
  },
  {
    name: 'Gass Forest Museum',
    city: 'Coimbatore',
    category: ['museum'],
    interests: ['nature', 'culture'],
    latitude: 11.0125,
    longitude: 76.9356,
    rating: 4.3,
    popularityScore: 78,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 40,
    description: 'Museum showcasing forest ecology, wildlife, and tribal heritage.',
    openingHours: '10:00 AM - 5:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Gass+Museum'
  },
  {
    name: 'Kovai Kutralam Waterfall',
    city: 'Coimbatore',
    category: ['nature'],
    interests: ['nature'],
    latitude: 10.8950,
    longitude: 76.8450,
    rating: 4.2,
    popularityScore: 72,
    mustSee: false,
    visitDurationHours: 2.5,
    entryFee: 30,
    description: 'Picturesque waterfall surrounded by lush greenery and trekking trails.',
    openingHours: '6:00 AM - 6:00 PM',
    bestSeason: 'June to December',
    imageUrl: 'https://via.placeholder.com/400x300?text=Kovai+Kutralam'
  },
  {
    name: 'Black Thunder Water Park',
    city: 'Coimbatore',
    category: ['recreation'],
    interests: ['relaxation'],
    latitude: 11.0200,
    longitude: 77.0150,
    rating: 4.0,
    popularityScore: 68,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 350,
    description: 'Adventure water park with slides, pools, and family-friendly attractions.',
    openingHours: '10:00 AM - 6:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Water+Park'
  },
  {
    name: 'Dhyanalinga Temple',
    city: 'Coimbatore',
    category: ['temple'],
    interests: ['temple', 'spirituality'],
    latitude: 10.9300,
    longitude: 76.6200,
    rating: 4.5,
    popularityScore: 82,
    mustSee: false,
    visitDurationHours: 2,
    entryFee: 0,
    description: 'Unique meditation temple with a powerful energy vortex. Peaceful ambiance.',
    openingHours: '6:00 AM - 8:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Dhyanalinga'
  },
  {
    name: 'Coimbatore Sports Complex',
    city: 'Coimbatore',
    category: ['sports'],
    interests: ['relaxation'],
    latitude: 11.0350,
    longitude: 76.9100,
    rating: 4.0,
    popularityScore: 55,
    mustSee: false,
    visitDurationHours: 1.5,
    entryFee: 100,
    description: 'Modern sports facility with swimming pools, courts, and recreation areas.',
    openingHours: '6:00 AM - 9:00 PM',
    bestSeason: 'All year',
    imageUrl: 'https://via.placeholder.com/400x300?text=Sports+Complex'
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/tntourism');
    
    console.log('Connected to MongoDB');
    
    // Clear existing data
    await Destination.deleteMany({});
    console.log('Cleared existing destinations');
    
    // Insert new data
    const result = await Destination.insertMany(destinations);
    console.log(`✅ Successfully seeded ${result.length} destinations`);
    
    // Show summary
    const cities = ['Thanjavur', 'Kanchipuram', 'Madurai', 'Chennai', 'Ooty', 'Coimbatore'];
    for (const city of cities) {
      const count = await Destination.countDocuments({ city });
      console.log(`${city}: ${count} destinations`);
    }
    
    process.exit(0);
  } catch (err) {
    console.error('Error seeding database:', err);
    process.exit(1);
  }
}

seedDatabase();
